version: 2
updates:
  - package-ecosystem: npm
    directory: /
    labels: [dependencies, automerge]
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      production-deps:
        dependency-type: production
      dev-deps:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - automerge
